src/main/java/model/BusinessProposal.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;

/**
 *
 * @author realnot
 */
public class BusinessProposal implements Serializable {
    
    // Constants ------------------------------------------------------
    private static final long serialVersionUID = 1L;
    
    // Properties -----------------------------------------------------
    private Integer proposal_id;
    private String proposal_name;
    private String proposal_desc;
    private Integer consulting_service;
    private String service_name; 
    
    // Getters/setters ------------------------------------------------
    public Integer getProposalID() { return this.proposal_id; }
    public String getProposalName() { return this.proposal_name; }
    public String getProposalDesc() { return this.proposal_desc; }
    public Integer getConsultingService() { return this.consulting_service; }
    public String getServiceName() { return this.service_name; }
    
    public void setProposalID(Integer value) { this.proposal_id = value; }
    public void setProposalName(String value) { this.proposal_name = value; }
    public void setProposalDesc(String value) { this.proposal_desc = value; }
    public void setConsultingService(Integer value) { this.consulting_service = value; }
    public void setServiceName(String value) { this.service_name = value; }
   
}

src/main/java/model/ConsultingService.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.Date;

/**
 *
 * @author realnot
 */
public class ConsultingService {
    
    // Constants ------------------------------------------------------
    private static final long serialVersionUID = 1L;
    
    // Properties -----------------------------------------------------
    private Integer service_id;
    private String service_name;
    private String service_desc;
    
    // Getters/setters ------------------------------------------------
    public Integer getServiceID() { return this.service_id; }
    public String getServiceName() { return this.service_name; }
    public String getServiceDesc() { return this.service_desc; }
    
    public void setServiceID(Integer value) { this.service_id = value; }
    public void setServiceName(String value) { this.service_name = value; }
    public void setServiceDesc(String value) { this.service_desc = value; }
}

src/main/java/model/Customer.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.Date;

/**
 *
 * @author realnot
 */
public class Customer {
    
    // Constants ------------------------------------------------------
    private static final long serialVersionUID = 1L;
    
    // Properties -----------------------------------------------------
    private Integer customer_id;
    private String customer_name;
    private String customer_email;
    private Integer customer_type;
    private Integer customer_category;
    private Date customer_created_on;
    private Integer customer_created_by;
    private Integer customer_assigned_to;
    private String customer_contact_name;
    private String customer_contact_surname;
    private String customer_contact_address;
    private String customer_contact_phone;
    
    private String string_customer_created_by;
    private String string_customer_assigned_to;
    private String string_customer_type;
    private String string_customer_category;
    
    // Getters/setters ------------------------------------------------
    public Integer getCustomerID() { return this.customer_id; }
    public String getCustomerName() { return this.customer_name; }
    public String getCustomerEmail() { return this.customer_email; }
    public Integer getCustomerCategory() { return this.customer_category; }
    public Integer getCustomerType() { return this.customer_type; }
    public Date getCustomerCreatedOn() { return this.customer_created_on; }
    public Integer getCustomerCreatedBy() { return this.customer_created_by; }
    public Integer getCustomerAssignedTo() { return this.customer_assigned_to; }
    public String getCustomerContactName() { return this.customer_contact_name; }
    public String getCustomerContactSurname() { return this.customer_contact_surname; }
    public String getCustomerContactAddress() { return this.customer_contact_address; }
    public String getCustomerContactPhone() { return this.customer_contact_phone; }
    public String getStringCustomerCategory() { return this.string_customer_category; }
    public String getStringCustomerType() { return this.string_customer_type; }
    public String getStringCustomerCreatedBy() { return this.string_customer_created_by; }
    public String getStringCustomerAssignedTo() { return this.string_customer_assigned_to; }
    
    public void setCustomerID(Integer value) { this.customer_id = value; }
    public void setCustomerName(String value) { this.customer_name = value; }
    public void setCustomerEmail(String value) { this.customer_email = value; }
    public void setCustomerCategory(Integer value) { this.customer_category = value; }
    public void setCustomerType(Integer value) { this.customer_type = value; }
    public void setCustomerCreatedOn(Date value) { this.customer_created_on = value; }
    public void setCustomerCreatedBy(Integer value) { this.customer_created_by = value; }
    public void setCustomerAssignedTo(Integer value) { this.customer_assigned_to = value; }
    public void setCustomerContactName(String value) { this.customer_contact_name = value; }
    public void setCustomerContactSurname(String value) { this.customer_contact_surname = value; }
    public void setCustomerContactAddress(String value) { this.customer_contact_address = value; }
    public void setCustomerContactPhone(String value) { this.customer_contact_phone = value; }
    public void setStringCustomerCategory(String value) { this.string_customer_category = value; }
    public void setStringCustomerType(String value) { this.string_customer_type = value; }
    public void setStringCustomerCreatedBy(String value) { this.string_customer_created_by = value; }
    public void setStringCustomerAssignedTo(String value) { this.string_customer_assigned_to = value; }

    
}

src/main/java/model/CustomerType.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author realnot
 */
public class CustomerType {
    
    // Constants ------------------------------------------------------
    private static final long serialVersionUID = 1L;
    
    // Properties -----------------------------------------------------
    private Integer customer_type_id;
    private String customer_type_name;
    private String customer_type_desc;
    
    // Getters/setters ------------------------------------------------
    public Integer getCustomerTypeID() { return this.customer_type_id; }
    public String getCustomerTypeName() { return this.customer_type_name; }
    public String getCustomerTypeDesc() { return this.customer_type_desc; }
    
    public void setCustomerTypeID(Integer value) { this.customer_type_id = value; }
    public void setCustomerTypeName(String value) { this.customer_type_name = value; }
    public void setCustomerTypeDesc(String value) { this.customer_type_desc = value; }
}

src/main/java/model/ProductCategory.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author realnot
 */
public class ProductCategory {
    
    // Constants ------------------------------------------------------
    private static final long serialVersionUID = 1L;
    
    // Properties -----------------------------------------------------
    private Integer product_id;
    private String product_name;
    private String product_desc;
    
    // Getters/setters ------------------------------------------------
    public Integer getProductID() { return this.product_id; }
    public String getProductName() { return this.product_name; }
    public String getProductDesc() { return this.product_desc; }
    
    public void setProductID(Integer value) { this.product_id = value; }
    public void setProductName(String value) { this.product_name = value; }
    public void setProductDesc(String value) { this.product_desc = value; }
}

src/main/java/model/Role.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;

/**
 *
 * @author realnot
 */
public class Role implements Serializable {
    
    // Constants ------------------------------------------------------
    private static final long serialVersionUID = 1L;
    
    // Properties -----------------------------------------------------
    private Integer role_id;
    private String role_name;
    private String role_desc;
    
    // Getters/setters ------------------------------------------------
    public Integer getRoleID() { return this.role_id; }
    public String getRoleName() { return this.role_name; }
    public String getRoleDesc() { return this.role_desc; }
    
    public void setRoleID(Integer value) { this.role_id = value; }
    public void setRoleName(String value) { this.role_name = value; }
    public void setRoleDesc(String value) { this.role_desc = value; }
}

src/main/java/model/UserProfile.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.sql.Timestamp;
import java.util.Date;

/**
 *
 * @author realnot
 */
public class UserProfile {
    
    // Constants ------------------------------------------------------
    private static final long serialVersionUID = 1L;
    
    // Properties -----------------------------------------------------
    private Integer user_id;
    private Integer role_id;
    private String username;
    private String password;
    private String email;
    private Integer lang_id;
    private String name;
    private String surname;
    private String display_name;
    private Integer gender_id;
    private Integer country_id;
    private Integer region_id;
    private Integer city_id;
    private String address;
    private String birthdate;
    private Timestamp created_on;
    private Timestamp last_login;
    private String role_name;
    
    // Getters/setters ------------------------------------------------
    
    public Integer getUserID() { return user_id; }
    public void setUserID(Integer value) { this.user_id = value; }
    
    public Integer getRoleID() { return role_id; }
    public void setRoleID(Integer value) { this.role_id = value; }
    
    public Integer getLangID() { return lang_id; }
    public void setLangID(Integer value) { this.lang_id = value; }
    
    public Integer getGenderID() { return gender_id; }
    public void setGenderID(Integer value) { this.gender_id = value; }
    
    public Integer getCountryID() { return country_id; }
    public void setCountryID(Integer value) { this.country_id = value; }
    
    public Integer getRegionID() { return region_id; }
    public void setRegionID(Integer value) { this.region_id = value; }
    
    public Integer getCityID() { return city_id; }
    public void setCityID(Integer value) { this.city_id = value; } 
    
    // The username can't be modified
    public String getUsername() { return username; }
    public void setUsername(String value) { this.username = value; }
    
    public String getPassword() { return password; }
    public void setPassword(String value) { this.password = value; }
    
    public String getEmail() { return email; }
    public void setEmail(String value) { this.email = value; }
    
    public String getName() { return name; }
    public void setName(String value) { this.name = value; }
    
    public String getSurname() {return surname; }
    public void setSurname(String value) { this.surname = value; }
    
    public String getDisplayName() { return display_name; }
    public void setDisplayName(String value) { this.display_name = value; }
    
    public String getAddress() { return address; }
    public void setAddress(String value) { this.address = value; }
    
    public String getBirthdate() { return birthdate; }
    public void setBirthdate(String value) { this.birthdate = value; }
    
    // The creation date of account can't be modified
    public Date getCreatedOn() { return created_on; }
    public void setCreatedOn(Timestamp value) { this.created_on = value; }
    
    // The last login date can't be modified
    public Date getLastLogin() { return last_login; }
    public void setLastLogin(Timestamp value) { this.last_login = value; } 
    
    public String getRoleName() { return role_name; }
    public void setRoleName(String value) { this.role_name = value; }
}

src/main/webapp/pages/BusinessProposalDetails.jsp
<%-- 
    Document   : BusinessProposalDetail
    Created on : May 26, 2015, 9:42:53 PM
    Author     : realnot
--%>

<!DOCTYPE html>
<html>
    <%@include file="include/head.jsp" %>
    <body>
        <div id="container">
            <div id="header">
                <%@include file="include/header.jsp" %> 
            </div>
            <div id="page" class="container container_16">
                <div id="nav" class="grid_4">
                    <%@include file="include/navigation.jsp" %>
                </div>
                <div id="meeting-details" class="grid_12 content">
                    <h3>Business Proposal Details</h3>
                    <table>
                        <tbody>
                            <tr>
                                <td>Code</td>
                                <td><c:out value="${details.proposalID}" /></td>
                            </tr>
                            <tr>
                                <td>Name</td>
                                <td><c:out value="${details.proposalName}" /></td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td><c:out value="${details.proposalDesc}" /></td>
                            </tr>
                            <tr>
                                <td>Consulting Service</td>
                                <td><c:out value="${details.serviceName}" /></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td><button onClick="location.href='BusinessProposalServlet?page=update&proposal_id=${details.proposalID}'" class="button-small update-entry" /> </td>
                                <td>
                                    <form action="BusinessProposalServlet" method="POST">
                                        <input type="hidden" name="action" value="delete" />
                                        <input type="hidden" name="proposalID" value="${details.proposalID}" />
                                        <input type="submit" class="button-submit-small del-entry" />
                                    </form>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div class='clear'>&nbsp;</div>
        </div>
        <div id="footer">
            <%@include file="include/footer.html" %>
        </div>
    </body>
</html> 

src/main/webapp/pages/ConsultingService.jsp
<%-- 
    Document   : ConsultingService
    Created on : May 20, 2015, 4:42:41 PM
    Author     : realnot
--%>

<!DOCTYPE html>
<html>
    <%@include file="include/head.jsp" %>
    <body>
        <div id="container">
            <div id="header">
                <%@include file="include/header.jsp" %> 
            </div>
            <div id="page" class="container container_16">
                <div id="nav" class="grid_4">
                    <%@include file="include/navigation.jsp" %>
                </div>
                <div id="customer-list" class="grid_12 content entry-list">
                    <h3>Consulting Services</h3>
                    <table>
                        <thead>
                            <tr>
                                <th>Code</th>
                                <th>Service</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                        <c:forEach items="${list}" var="l">
                            <tr onClick="location.href='ConsultingServiceServlet?page=details&service_id=${l.serviceID}'">
                                <td><c:out value="${l.serviceID}" /></td>
                                <td><c:out value="${l.serviceName}" /></td>
                                <td><c:out value="${l.serviceDesc}" /></td>
                            </tr>
                        </c:forEach>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td><button onClick="location.href='ConsultingServiceServlet?page=create'" class="button add-cs" /></td>
                                <td><button onClick="location.href='ConsultingServiceServlet?page=find'" class="button find-entry" /></td>
                                <td colspan="1">&nbsp;</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                </div>
                <div class='clear'>&nbsp;</div>
        </div>
        <div id="footer">
            <%@include file="include/footer.html" %>
        </div>
    </body>
</html> 

src/main/webapp/pages/ConsultingServiceDetails.jsp
<%-- 
    Document   : ConsultingServiceDetail
    Created on : May 27, 2015, 3:20:03 PM
    Author     : realnot
--%>

<!DOCTYPE html>
<html>
    <%@include file="include/head.jsp" %>
    <body>
        <div id="container">
            <div id="header">
                <%@include file="include/header.jsp" %> 
            </div>
            <div id="page" class="container container_16">
                <div id="nav" class="grid_4">
                    <%@include file="include/navigation.jsp" %>
                </div>
                <div id="consulting-service-details" class="grid_12 content">
                    <h3>Consulting Service Details</h3>
                    <table>
                        <tbody>
                            <tr>
                                <td>Code</td>
                                <td><c:out value="${details.serviceID}" /></td>
                            </tr>
                            <tr>
                                <td>Name</td>
                                <td><c:out value="${details.serviceName}" /></td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td><c:out value="${details.serviceDesc}" /></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td><button onClick="location.href='ConsultingServiceServlet?page=update&service_id=${details.serviceID}'" class="button-small update-entry" /> </td>
                                <td>
                                    <form action="ConsultingServiceServlet" method="POST">
                                        <input type="hidden" name="action" value="delete" />
                                        <input type="hidden" name="serviceID" value="${details.serviceID}" />
                                        <input type="submit" class="button-submit-small del-entry" />
                                    </form>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div class='clear'>&nbsp;</div>
        </div>
        <div id="footer">
            <%@include file="include/footer.html" %>
        </div>
    </body>
</html> 

src/main/webapp/pages/Customer.jsp
<%-- 
    Document   : Customer
    Created on : May 6, 2015, 3:44:20 PM
    Author     : realnot
--%>

<!DOCTYPE html>
<html>
    <%@include file="include/head.jsp" %>
    <body>
        <div id="container">
            <div id="header">
                <%@include file="include/header.jsp" %> 
            </div>
            <div id="page" class="container container_16">
                <div id="nav" class="grid_4">
                    <%@include file="include/navigation.jsp" %>
                </div>
                <div id="customer-list" class="grid_7 content entry-list">
                    <h3>Recent Customers</h3>
                    <table>
                        <thead>
                            <tr>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                        <tbody>
                        <c:forEach items="${list}" var="l">
                        <a href="CustomerDetails.jsp">
                            <tr onClick="location.href='CustomerServlet?page=details&customer_id=${l.customerID}'">
                                <td><c:out value="${l.customerID}" /></td>
                                <td><c:out value="${l.customerName}" /></td>
                                <td><c:out value="${l.customerEmail}" /></td>
                            </tr>
                        </a>
                        </c:forEach>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td><button onClick="location.href='CustomerServlet?page=create'" class="button add-customer" /></td>
                                <td><button onClick="location.href='CustomerServlet?page=find'" class="button find-entry" /></td>
                                <td colspan="1">&nbsp;</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                </div>
                <div class='clear'>&nbsp;</div>
        </div>
        <div id="footer">
            <%@include file="include/footer.html" %>
        </div>
    </body>
</html> 

src/main/webapp/pages/CustomerCreate.jsp
<%-- 
    Document   : AddCustomer
    Created on : May 18, 2015, 10:20:39 PM
    Author     : realnot
--%>

<!DOCTYPE html>
<html>
    <%@include file="include/head.jsp" %>
    <body>
        <div id="container">
            <div id="header">
                <%@include file="include/header.jsp" %> 
            </div>
            <div id="page" class="container container_16">
                <div id="nav" class="grid_4">
                    <%@include file="include/navigation.jsp" %>
                </div>
                <div id="add-customer" class="grid_8 content">
                    <h3>Add a new customer</h3>
                    <form action="CustomerServlet" method="POST" class="crm-form crm-form-stacked">
                        <table class="">
                            <tr>
                                <td class="">
                                    <fieldset>
                                    <legend>Customer Details</legend>
                                    <div>
                                        <label for="customer-name">Customer Name</label>
                                        <input id="customer-name" name="customer-name" type="text" required>
                                    </div>
                                    <div>
                                        <label for="customer-email">Customer E-Mail</label>
                                        <input id="customer-email" name="customer-email" type="email" required>
                                    </div>
                                    <div>
                                        <label for="customer-type">Customer Type</label>
                                            <select id="assigned-to" name="customer-type">
                                                <c:forEach items="${types}" var="t">
                                                    <option value='<c:out value="${t.customerTypeID}"></c:out>'>
                                                        <c:out value="${t.customerTypeName}"></c:out></option>
                                                </c:forEach>
                                            </select>
                                    </div>
                                    <div>
                                        <label for="product-category">Customer Product Category</label>
                                            <select id="assigned-to" name="product-category">
                                                <c:forEach items="${categories}" var="c">
                                                    <option value='<c:out value="${c.productID}"></c:out>'>
                                                        <c:out value="${c.productName}"></c:out></option>
                                                </c:forEach>
                                            </select>
                                    </div>
                                    <div>
                                        <label for="assigned-to">Consultant</label>
                                            <select id="assigned-to" name="assigned-to">
                                                <c:forEach items="${users}" var="u">
                                                    <option value='<c:out value="${u.userID}"></c:out>'>
                                                        <c:out value="${u.username}"></c:out></option>
                                                </c:forEach>
                                            </select>
                                    </div>
                                    </fieldset>
                                </td>
                                <td class="">
                                    <fieldset>
                                        <legend>Company Agent</legend>
                                        <div>
                                            <label for="agent-name">Name</label>
                                            <input id="agent-name" name="agent-name" type="text" required>
                                        </div>
                                        <div>
                                            <label for="agent-surname">Surname</label>
                                            <input id="agent-surname" name="agent-surname" type="text" required>
                                        </div>
                                        <div>
                                            <label for="agent-address">Address</label>
                                            <input id="agent-address" name="agent-address" type="text" required>
                                        </div>
                                        <div>
                                            <label for="agent-phone">Phone</label>
                                            <input id="agent-phone" name="agent-phone" type="tel" required>
                                        </div>
                                    </fieldset>
                                </td>
                            </tr>
                            <tr>
                                <td class="">
                                    <fieldset>
                                        <legend>Business Proposals</legend>
                                        <div>
                                            <label for="proposals">Proposal name</label>
                                            <select id="proposals" name="proposalID" size="3">
                                                <c:forEach items="${proposals}" var="p">
                                                    <option value='<c:out value="${p.proposalID}"></c:out>'>
                                                        <c:out value="${p.proposalName}"></c:out></option>
                                                </c:forEach>
                                            </select>
                                        </div>
                                    </fieldset>
                                </td>
                                <td class="">
                                    <fieldset>
                                        <legend>Consulting Services</legend>
                                        <div>
                                            <label for="services">Service name</label>
                                            <select id="services" name="serviceID" size="3">
                                                <c:forEach items="${services}" var="s">
                                                    <option value='<c:out value="${s.serviceID}"></c:out>'>
                                                        <c:out value="${s.serviceName}"></c:out></option>
                                                </c:forEach>
                                            </select>
                                        </div>
                                    </fieldset>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <div>
                                        <input type="hidden" name="action" value="save">
                                        <input type="hidden" name="created-by" value="<c:out value="${login.userID}" />">
                                        <input type="submit" class="pure-button pure-button-primary" value="Save Customer">
                                        <input type="reset" value="Clear data">
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                <div class='clear'>&nbsp;</div>
            </div>
        </div>
        <div id="footer">
            <%@include file="include/footer.html" %>
        </div>
    </body>
</html> 